name: CD Workflow
on: [push]

jobs:
    test:
        runs-on: Ubuntu-latest
        env:
            ssh_key: ${{ secrets.SSH_KEY }}
        steps:
        - uses: actions/checkout@v3
        - name: Set ssh key
          run: |
            mkdir -p ~/.ssh && \
            echo "$ssh_key" | base64 -d > ~/.ssh/puk && \
            chmod 0600 ~/.ssh/puk

        
        - name: list remote dir
          run: ssh bdb2c2023q4_guest_3 ls
        
        - run: echo OK
