name: CI Workflow
on: [push]

jobs:
    test:
        runs-on: Windows-latest
        env:
            ssh_key: ${{ secrets.SSH_KEY }}
        steps:
        - uses: actions/checkout@v3
        - run:  mkdir -p ~/.ssh
        - run: echo $ssh_key > ~/id_rsa
        - run: ssh bdbc2c2023q4_guest_3@brain-client.bigdatateam.org ls 
        - run: python3 test_shuffle_key.py
        - run: echo OK
